# image de base
FROM python:latest

# on copie l'app
COPY . /app

#on va dans le dossier de l app
WORKDIR /app

RUN pip install --upgrade pip && pip install -r requirements.txt

# on lance le serveur flask
EXPOSE 5000
CMD gunicorn -c gunicorn.conf.py