# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.TTY/busymccarthy: "false"
    io.podman.annotations.autoremove/busymccarthy: "FALSE"
    io.podman.annotations.init/busymccarthy: "FALSE"
    io.podman.annotations.privileged/busymccarthy: "FALSE"
    io.podman.annotations.publish-all/busymccarthy: "FALSE"
    org.opencontainers.image.base.digest/busymccarthy: sha256:1310b65d525e6854ddc2a7efaf790b4db9347a6f6eab738145bc8bfb
    org.opencontainers.image.base.name/busymccarthy: python:latest
  creationTimestamp: "2024-08-25T08:14:59Z"
  labels:
    app: busymccarthy-pod
  name: busymccarthy-pod
spec:
  automountServiceAccountToken: false
  containers:
  - image: localhost/piweb:latest
    name: busymccarthy
    ports:
    - containerPort: 5000
      hostPort: 5000
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  enableServiceLinks: false

